# Pytorch Assignment - 01

### Explain five interesting Pytorch functions and explain them.

Functions explained are as follows :
- torch.zeros()
- torch.range()
- torch.narrow() 
- torch.reshape()
- torch.transpose()

In [2]:
# Import torch and other required modules
import torch

## Function 1 - torch.zeros()

It is used to create a tensor of scalar value 0 and the six=ze of the same is dividex by the size parameter passed in the function.

In [2]:
# Example 1 - tensor of size 2
torch.zeros(2)

tensor([0., 0.])

A tensor of size 2 is created with scaler value 0 , in float datatype.

In [3]:
# Example 2 
torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

A tensor of 2 dimensions is created with size passed as arguments to the function. We have created a tensore of size 2 cross 3 containing scalar 0 as its value.

In [4]:
# Example 3 
torch.zeros(-2)

RuntimeError: Trying to create tensor with negative dimension -2: [-2]

The function breaks here as we can't create tensors with negative dimensions hence our code breaks.

torch.zeros() can be used to initialize our torch tensor before we start working with it and can also be used to get the bitwise operations performed on the tensors.

## Function 2 - torch.range()

torch.range(start=0, end, step=1, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor
torch.range() has many parameters to input but the main being start and end, post execution we get a tensor starting from the start value till the end value passed in the arguments.

In [5]:
# Example 1 
torch.range(5,12)

/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  


tensor([ 5.,  6.,  7.,  8.,  9., 10., 11., 12.])

We get a tensor starting from the start value and ending at the end value and default step size being 1.

In [6]:
# Example 2 - working
torch.range(20,30,5)

/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  


tensor([20., 25., 30.])

In the above example we get a tensor output from the start value = 20 till end value = 30 and the step size being 5 as passed in the arguments.

In [12]:
# Example 3 - breaking
torch.range(-1,-12,2)


/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  


RuntimeError: upper bound and larger bound inconsistent with step sign

In the above example we have taken the upper bound and lower bound inconsistent with the size of step allowed to us, as we can never move to more negative values by taking a positive step.

torch.range(start,end,step) function can be used to generate desired tensors, here we have the control on the range of values present in the tensor.

## Function 3 - torch.narrow() 

torch.narrow(input, dim, start, length) → Tensor
Used to resize the tensor provided , the parameters entered are as follows :
input - takes in the input tensor on which the operation is to be done.
dim - axis along which the operation is to be done
start - index from where operation needs to start
length - length of the tensor output


In [2]:
# Example 1 - working
print("Initial tensor :")
x = torch.tensor([[0, 1, 2, 3], [1, 4, 5, 6], [2, 7, 8, 9], [3, 10,11,12]])
print(x)
print("After Narrowing the tensor :")
torch.narrow(x, 0, 1, 2)

Initial tensor :
tensor([[ 0,  1,  2,  3],
        [ 1,  4,  5,  6],
        [ 2,  7,  8,  9],
        [ 3, 10, 11, 12]])
After Narrowing the tensor :


tensor([[1, 4, 5, 6],
        [2, 7, 8, 9]])

We have entered the tensor x , we start at the index 1 along the axis 0 and we get 2 values starting from the index 1.
Explanation about example

In [3]:
# Example 2 - working
print("Initial tensor :")
x = torch.tensor([[0, 1, 2, 3], [1, 4, 5, 6], [2, 7, 8, 9], [3, 10,11,12]])
print(x)
print("After Narrowing the tensor :")
torch.narrow(x, 1, 0, 3)

Initial tensor :
tensor([[ 0,  1,  2,  3],
        [ 1,  4,  5,  6],
        [ 2,  7,  8,  9],
        [ 3, 10, 11, 12]])
After Narrowing the tensor :


tensor([[ 0,  1,  2],
        [ 1,  4,  5],
        [ 2,  7,  8],
        [ 3, 10, 11]])

We have entered the tensor x , we start at the index 0 along the axis 1 and we get 3 values starting from the index 1.


In [4]:
# Example 3 - breaking
print("Initial tensor :")
x = torch.tensor([[0, 1, 2, 3], [1, 4, 5, 6], [2, 7, 8, 9], [3, 10,11,12]])
print(x)
print("After Narrowing the tensor :")
torch.narrow(x, 2, 1, 2)


Initial tensor :
tensor([[ 0,  1,  2,  3],
        [ 1,  4,  5,  6],
        [ 2,  7,  8,  9],
        [ 3, 10, 11, 12]])
After Narrowing the tensor :


IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

Here we are tring to use the axis 2 which is not existent thus the function breaks.

tensor.narrow() function can be used when we need to filter out the unwanted data in the dataset we are tring to generate predictions from.
This could help us in enhancing and enriching the dataset to make better predictions and is very useful in data cleaning.

## Function 4 - torch.reshape()

torch.reshape(input, shape) → Tensor

In the function torch.reshape() we modify the shape of a tensor by passing in the tensor and the size of the new tensor we need.

In [19]:
# Example 1 - working
print("Initial tensor :")
x = torch.tensor([3, 7 , 9 , 2 , 18 , 100])
print(x)
print("After reshaping the tensor :")
torch.reshape(x,(2,3))


Initial tensor :
tensor([  3,   7,   9,   2,  18, 100])
After reshaping the tensor :


tensor([[  3,   7,   9],
        [  2,  18, 100]])

We created a tensor of size 8, now we reshaped it into a tensor of 2 cross 3 by calling the reshape command and passing into it the tensor x and the size we require.

In [22]:
# Example 2 - working
print("Initial tensor :")
x = torch.tensor([[3, 7 ],[ 9 , 2] , [18 , 100],[0, 6],[23,5]])
print(x)
print("After reshaping the tensor :")
torch.reshape(x,(2,5))


Initial tensor :
tensor([[  3,   7],
        [  9,   2],
        [ 18, 100],
        [  0,   6],
        [ 23,   5]])
After reshaping the tensor :


tensor([[  3,   7,   9,   2,  18],
        [100,   0,   6,  23,   5]])

We create a tensor of size (5, 2) and then we try to reshape it into a tensor of size (2,5) we are able to do so because we have enough elements to divide into two parts containing five elements each. If we don't have enough elements we will be unable to reshape the tensor.

The same is illustrated below.

In [23]:
# Example 3 - breaking 
print("Initial tensor :")
x = torch.tensor([[3, 7 , 45],[ 9 , 2, 78] , [18 , 100, 11], [0, 6, 8], [23, 5, 4]])
print(x)
print("After reshaping the tensor :")
torch.reshape(x,(2,5))


Initial tensor :
tensor([[  3,   7,  45],
        [  9,   2,  78],
        [ 18, 100,  11],
        [  0,   6,   8],
        [ 23,   5,   4]])
After reshaping the tensor :


RuntimeError: shape '[2, 5]' is invalid for input of size 15

As we can see here we have the initial tensor of size (5,3) and we wanted to change it to the shape (2,5) and thus it failed because we had more elements then we were tring to reshape it into.

We can use this function to :
1) Change the size of our tensor
2) Cleanse and enrich the data to perform calculations and operations on it

## Function 5 - torch.transpose()

torch.transpose(input, dim0, dim1) → Tensor

We are able to find the transpose of our supplied tensor using this function along the mentioned dimensions i.e. dim0 and dim1.

In [5]:
# Example 1 - working
x = torch.randn(5, 2)
print("Initial Tensor :")
print(x)
torch.transpose(x, 0, 1)

Initial Tensor :
tensor([[-0.0029,  1.0346],
        [ 1.2681, -0.5989],
        [ 0.0474,  0.5090],
        [-0.2817, -1.1246],
        [-0.7905,  0.9711]])


tensor([[-0.0029,  1.2681,  0.0474, -0.2817, -0.7905],
        [ 1.0346, -0.5989,  0.5090, -1.1246,  0.9711]])

torch.transpose() works similar to the matrix transpose we do in day to day life, here we create a tensor of size (5,2) and then find its transpose along axis 0 and 1 and we get a resulting tensor of size (2,5).

In [8]:
# Example 2 - working
x = torch.randn(5, 4)
print("Initial Tensor :")
print(x)
torch.transpose(x, 0, 1)


Initial Tensor :
tensor([[ 1.6601, -0.0946, -1.3786, -1.2378],
        [-1.9096,  0.1220,  0.9633, -0.3411],
        [ 0.0754,  0.2517, -1.0027,  0.6507],
        [ 0.0743, -0.2732, -1.5047,  0.1892],
        [ 0.7718, -0.3257, -0.1611, -0.3330]])


tensor([[ 1.6601, -1.9096,  0.0754,  0.0743,  0.7718],
        [-0.0946,  0.1220,  0.2517, -0.2732, -0.3257],
        [-1.3786,  0.9633, -1.0027, -1.5047, -0.1611],
        [-1.2378, -0.3411,  0.6507,  0.1892, -0.3330]])

torch.transpose() works similar to the matrix transpose we do in day to day life, here we create a tensor of size (5,4) and then find its transpose along axis 0 and 1 and we get a resulting tensor of size (4,5).

In [10]:
# Example 3 - breaking 
x = torch.randn(5, 3)
print("Initial Tensor :")
print(x)
torch.transpose(x, 2, 1)

Initial Tensor :
tensor([[ 0.8846, -0.3575, -1.0857],
        [-0.0374, -0.2319,  0.1997],
        [-1.8523, -1.6584,  0.0986],
        [ 0.0149,  1.0128,  1.6954],
        [-0.2058,  0.4817, -1.2779]])


IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

Here the function torch.transpose breaks as we have supplied the value of axis to be 2 and 1 but we only have axis available in the range [-2 , 1], and hence our function breaks.

We can use this function whenever we need to find the transpose of the torch tensor which will help us in further making the calculations on larger models easier and efficient.

## Conclusion

In this notebook we have discovered some of the very interesting functions available in the PyTorch Library and have discussed the aspects how these functions can be used and implemented and how they can proove useful to us.


## Reference Links

* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html


In [12]:
!pip install jovian --upgrade --quiet

In [13]:
import jovian

In [15]:
jovian.commit()


<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "pathak-vineeta786/assignment-1" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/pathak-vineeta786/assignment-1


'https://jovian.ml/pathak-vineeta786/assignment-1'